services:
  - type: web
    name: skin-cancer-classifier-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && python api_server.py
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
